# mypy: ignore-errors

"""
Create vacancy, salary and rating tables

Revision ID: d32bd195d834
Revises:
Create Date: 2026-03-19 12:21:12.824724
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d32bd195d834"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rating",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "company_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salary",
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("grade", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "specialization",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("salary_min", sa.Integer(), nullable=False),
        sa.Column("salary_max", sa.Integer(), nullable=False),
        sa.Column(
            "salary_currency",
            sa.Enum("RUB", "USD", "EUR", name="currency"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("source", "title", "grade"),
    )
    op.create_table(
        "vacancy",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "company_logo_url",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "position_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "raw_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "location", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "salary_raw", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column(
            "salary_currency",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("salary_gross", sa.Boolean(), nullable=True),
        sa.Column(
            "work_format", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "employment_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("published_at", sa.Integer(), nullable=False),
        sa.Column(
            "grade_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "specialization_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "domain_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "skill_ids", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "tool_ids", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "embedding", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "attributes", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vacancy")
    op.drop_table("salary")
    op.drop_table("rating")
    # ### end Alembic commands ###
