keywords: 
  - программист
  - програмист
  - разработчик
  - programmer
  - developer
  - тестировщик
  - аналитик
  - data science
  - data scientist
  - devops
  - системный администратор
  - machine learning
  - mlops
  - дизайнер
  - designer
  - руководитель проектов
  - проджект менеджер
  - project manager
  - продакт менеджер
  - product manager

exclude:
  - 1с
  - тьютор
  - преподаватель
  - продавец
  - продаж
  - маркет
  - ozon
  - озон
  - wb
  - wildberries
  - вайлдбери
  - smm
  - закуп
  - одежд
  - мебел
  - кух
  - интерьер
  - штор
  - салон
  - текстил
  - кондит
  - игруш
  - чпу
  - станк
  - кредит
  - консульта
  - фотограф
  - прораб
  - архитектор
  - достав
  - флори
  - бухгалт
  - технолог
  - электромонтаж