global_exclude:
  [1с, вайбкод, тьютор, преподаватель, продавец, продаж, маркет, ozon, озон, wb
  wildberries, вайлдбери, smm, закуп, одежд, мебел, кух, интерьер, штор, салон
  текстил, кондит, игруш, чпу, станк, асу, кредит, консульта, фото, прораб
  архитектор, достав, флори, бухгалт, финансовый, экономист, технолог, вышив
  электромонтаж, типограф, ландшафт, копицентр, печат, химик, полиграф, швея
  территор, велотур, call]

search_groups:
  - keywords: 
    - программист
    - програмист
    - разработчик
    - developer
    - тестировщик
    - аналитик
    - системный администратор
    - дизайнер
    - designer

    exclude: [1с]
